os:
  - linux-ppc64le
  - linux
language: node_js
sudo: false
node_js:
  - "0.10"
  - 0.12
  - iojs
  - 4
  - 5
env:
  - CXX=g++-4.8
matrix:
  exclude:
  - os: linux-ppc64le
    node_js: "0.10"
  - os: linux-ppc64le
    node_js: 0.12
  - os: linux-ppc64le
    node_js: iojs
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email:
    - andris@kreata.ee
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0ed18fd9b3e529b3c2cc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
